# Every file the harness touches, so that touching one is an injected dependency.
import pathlib
import typing


class FileSystem(typing.Protocol):
    def read_text(self, path: pathlib.PurePath) -> str: ...

    def write_text(self, path: pathlib.PurePath, text: str) -> None: ...

    def read_bytes(self, path: pathlib.PurePath) -> bytes: ...

    def mkdir(
        self, path: pathlib.PurePath, parents: bool = False, exist_ok: bool = False
    ) -> None: ...

    def unlink(self, path: pathlib.PurePath) -> None: ...

    def iterdir(self, path: pathlib.PurePath) -> tuple[pathlib.PurePath, ...]: ...

    def glob(self, path: pathlib.PurePath, pattern: str) -> tuple[pathlib.PurePath, ...]: ...

    def mtime(self, path: pathlib.PurePath) -> float: ...

    def exists(self, path: pathlib.PurePath) -> bool: ...

    def is_file(self, path: pathlib.PurePath) -> bool: ...

    def is_dir(self, path: pathlib.PurePath) -> bool: ...

    def resolve(self, path: pathlib.PurePath) -> pathlib.PurePath: ...

    def expanduser(self, path: pathlib.PurePath) -> pathlib.PurePath: ...

    def open_append(self, path: pathlib.PurePath) -> typing.TextIO: ...

    def open_write(self, path: pathlib.PurePath) -> typing.TextIO: ...
