# Every file the harness touches, so that touching one is an injected dependency.
import pathlib
import typing


class FileSystem(typing.Protocol):
    def read_text(self, path: pathlib.Path) -> str: ...

    def write_text(self, path: pathlib.Path, text: str) -> None: ...

    def read_bytes(self, path: pathlib.Path) -> bytes: ...

    def mkdir(self, path: pathlib.Path, parents: bool = False, exist_ok: bool = False) -> None: ...

    def unlink(self, path: pathlib.Path) -> None: ...

    def iterdir(self, path: pathlib.Path) -> tuple[pathlib.Path, ...]: ...

    def glob(self, path: pathlib.Path, pattern: str) -> tuple[pathlib.Path, ...]: ...

    def exists(self, path: pathlib.Path) -> bool: ...

    def is_file(self, path: pathlib.Path) -> bool: ...

    def is_dir(self, path: pathlib.Path) -> bool: ...

    def open_append(self, path: pathlib.Path) -> typing.TextIO: ...

    def open_write(self, path: pathlib.Path) -> typing.TextIO: ...
